# Generated by Django 5.1.2 on 2025-03-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('loopit', '0002_customuser_alter_profile_user_delete_loopituser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='LoopitUser',
        ),
    ]
