# Generated by Django 5.1.5 on 2025-04-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopit', '0006_alter_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/'),
        ),
    ]
