# Generated by Django 5.1.5 on 2025-04-24 09:11

import loopit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopit', '0007_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to=loopit.models.user_directory_path),
        ),
    ]
